name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - Elius94
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: What should have happened?
      description: Tell us, what did you expect to happen?
      placeholder: Tell us what you expected!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code
      description: Please provide a code that you are trying to run
      placeholder: |
        ```js
        // Your code here
        ```
    validations:
      required: false
  - type: textarea
    id: sandbox-link
    attributes:
      label: Sandbox Link
      description: Please provide a link to a sandbox that reproduces the issue
      placeholder: https://codesandbox.io/s/...
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: Library Version
      description: What version of the lib are you using?
      placeholder: "latest"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      options:
        - Windows
        - macOS
        - Ubuntu
        - Other Linux
        - Other
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide logs
      placeholder: |
        ```log
        // Your logs here
        ```
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Interest to fix the bug
      description: Are you interested in fixing this bug?
      options:
        - label: I would like to fix this bug!
          required: false